In [10]:
import pandas as pd
import csv

In [13]:
with open("real_drug_dataset.csv",'r') as d:
    res = csv.reader(d)
    data = pd.DataFrame(res)
data.head()

,0,1,2,3,4,5,6,7,8
0,ï»¿Patient_ID,Age,Gender,Condition,Drug_Name,Dosage_mg,Treatment_Duration_days,Side_Effects,Improvement_Score
1,P0001,56,Male,Infection,Ciprofloxacin,50,9,Nausea,8.5
2,P0002,69,Male,Hypertension,Metoprolol,500,24,Tiredness,8.7
3,P0003,46,Female,Depression,Bupropion,100,25,Dry mouth,5.4
4,P0004,32,Male,Diabetes,Glipizide,850,44,Low blood sugar,6.4

In [17]:
t = pd.read_csv("real_drug_dataset.csv")
t.head()

,Patient_ID,Age,Gender,Condition,Drug_Name,Dosage_mg,Treatment_Duration_days,Side_Effects,Improvement_Score
0,P0001,56,Male,Infection,Ciprofloxacin,50,9,Nausea,8.5
1,P0002,69,Male,Hypertension,Metoprolol,500,24,Tiredness,8.7
2,P0003,46,Female,Depression,Bupropion,100,25,Dry mouth,5.4
3,P0004,32,Male,Diabetes,Glipizide,850,44,Low blood sugar,6.4
4,P0005,60,Male,Depression,Bupropion,850,35,Anxiety,5.3

1. Read specific columns using read_csv

In [18]:
temp = pd.read_csv("real_drug_dataset.csv",usecols=["Age","Gender"])
temp.head()

   Age  Gender
0   56    Male
1   69    Male
2   46  Female
3   32    Male
4   60    Male

2.Setting an Index Column (index_col)

In [20]:
temp = pd.read_csv("real_drug_dataset.csv",index_col=0)
temp.head()

,Age,Gender,Condition,Drug_Name,Dosage_mg,Treatment_Duration_days,Side_Effects,Improvement_Score
Patient_ID,,,,,,,,
P0001,56,Male,Infection,Ciprofloxacin,50,9,Nausea,8.5
P0002,69,Male,Hypertension,Metoprolol,500,24,Tiredness,8.7
P0003,46,Female,Depression,Bupropion,100,25,Dry mouth,5.4
P0004,32,Male,Diabetes,Glipizide,850,44,Low blood sugar,6.4
P0005,60,Male,Depression,Bupropion,850,35,Anxiety,5.3

3. Handling Missing Values Using read_csv

In [24]:
temp = pd.read_csv("real_drug_dataset.csv",na_values=["N/A", "Unknown"])
temp.head()

,Patient_ID,Age,Gender,Condition,Drug_Name,Dosage_mg,Treatment_Duration_days,Side_Effects,Improvement_Score
0,P0001,56,Male,Infection,Ciprofloxacin,50,9,Nausea,8.5
1,P0002,69,Male,Hypertension,Metoprolol,500,24,Tiredness,8.7
2,P0003,46,Female,Depression,Bupropion,100,25,Dry mouth,5.4
3,P0004,32,Male,Diabetes,Glipizide,850,44,Low blood sugar,6.4
4,P0005,60,Male,Depression,Bupropion,850,35,Anxiety,5.3

4. Using skiprows in read_csv()

In [26]:
temp = pd.read_csv("real_drug_dataset.csv",skiprows=[2,3,4,5,6])
temp.head()

,Patient_ID,Age,Gender,Condition,Drug_Name,Dosage_mg,Treatment_Duration_days,Side_Effects,Improvement_Score
0,P0001,56,Male,Infection,Ciprofloxacin,50,9,Nausea,8.5
1,P0007,78,Male,Diabetes,Glipizide,250,40,Nausea,6.5
2,P0008,38,Male,Pain Relief,Paracetamol,100,15,Liver issues,8.2
3,P0009,56,Male,Depression,Escitalopram,850,56,Nausea,9.0
4,P0010,75,Male,Diabetes,Metformin,850,19,Nausea,9.1